<?xml version = "1.0" encoding = "UTF-8"?>

<!--Internal DTD-->
<!DOCTYPE recipes [
<!--+ one or more, * zero or more, ? zero or one-->
<!--must add two tags?-->
<!ELEMENT recipes (recipe+, creator+)>
    <!ATTLIST recipes type CDATA "Asian">
  <!ELEMENT recipe (chef?, origin, title, ingredients+, instructions+, time+,
  serves+, properties+, difficulty+, tastylevel+,url+,img+)>
  <!ELEMENT chef (givenname, surname)>  <!--attribute is nationality-->
    <!ATTLIST chef nationality CDATA "America">
  <!ELEMENT givenname (#PCDATA)>
  <!ELEMENT surname (#PCDATA)>
  <!ELEMENT nationality (#PCDATA)>
  <!ELEMENT origin (#PCDATA)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT ingredients (main+, ingredient*)>
  <!ELEMENT main (#PCDATA)>
  <!ELEMENT ingredient (#PCDATA)>
  <!ELEMENT instructions (#PCDATA)>
  <!ELEMENT time (hours?, minutes?, seconds?)>
  <!ELEMENT hours (#PCDATA)>
  <!ELEMENT minutes (#PCDATA)>
  <!ELEMENT seconds (#PCDATA)>
  <!ELEMENT serves (#PCDATA)>
  <!ELEMENT properties (#PCDATA)>
  <!ELEMENT difficulty (#PCDATA)>
  <!ELEMENT tastylevel (#PCDATA)>
  <!ELEMENT url (#PCDATA)>
  <!ELEMENT img (#PCDATA)>
  <!ELEMENT creator (#PCDATA)>
  <!ENTITY author "Juyong Kim">         <!--entity required-->
  <!ENTITY copyright "Copyright c32244203">
  <!--<author>&author;&copyright;</author>-->
]>

<!--standard xml template-->
<recipes>
    <recipe>
        <chef>
            <givenname>Gordan</givenname>
            <surname>Ramsey</surname>
        </chef>
        <origin></origin>
        <title></title>
        <ingredients>
            <main>Toast</main>
            <ingredient></ingredient>
            <ingredient></ingredient>
        </ingredients>
        <instructions>cover 2 pieces of bread in butter both sides</instructions>
        <time>
            <minutes>0</minutes>
        </time>
        <serves>2</serves>
        <properties>vegetarian</properties>
        <difficulty>easy</difficulty>
        <tastylevel>5</tastylevel>
        <url>https://en.wikipedia.org/wiki/Vegan_cheese</url>
        <img>"vegancheese.jpeg"</img>
    </recipe>
    <creator>
        &author;
        &copyright;
    </creator>
</recipes>
